import Head from 'next/head'
import type { NextPage } from 'next'
import useUser from 'hooks/useUser'
import styles from 'styles/Messenger.module.css'
import Message from 'components/Message/Message'
import useConversations from 'hooks/useConversations'
import ChatOnline from 'components/ChatOnline/ChatOnline'
import Conversation from 'components/Conversations/Conversation'
import useCurrentConversation from 'hooks/useCurrentConversation'

const Messenger : NextPage = () => {
  const { userId } = useUser()
  const conversations = useConversations()
  const { currentConversation, messages, onChangeConversation } = useCurrentConversation()

  let chatContainer:any = messages.map((m:any) => (
    <Message
      key={m.id}
      own={parseInt(m.sender, 10) === userId}
      text={m.text}
      createdAt={m.createdAt}
    />
  ))

  if (messages.length === 0) {
    chatContainer = (
      <div className={styles.emptyContainer}>
        <p className={styles.emptyText}>No hay mensajes</p>
      </div>
    )
  }

  if (!currentConversation) {
    chatContainer = (
      <div className={styles.emptyContainer}>
        <p className={styles.emptyText}>Open a conversation to start a chat.</p>
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Messenger Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.messenger}>
        <div className={styles.chatMenu}>
          <div className={styles.chatMenuWrapper}>
            <input placeholder="Search for friends" className={styles.chatMenuInput} />
            {conversations.map((c:any) => (
              <Conversation
                key={c.id}
                name={c.name}
                imageUrl={c.imageUrl}
                onClick={() => onChangeConversation(c)}
              />
            ))}
          </div>
        </div>
        <div className={styles.chatBox}>
          <div className={styles.chatBoxWrapper}>
            <div className={styles.chatBoxTop}>
              {chatContainer}
            </div>
            <div className={styles.chatBoxBottom}>
              <textarea
                className={styles.chatMessageInput}
                placeholder="write something"
              />
              <button
                type="button"
                className={styles.chatSubmitButton}
              >
                Send
              </button>
            </div>
          </div>
        </div>
        <div className={styles.chatOnline}>
          <div className={styles.chatOnlineWrapper}>
            <ChatOnline />
            <ChatOnline />
            <ChatOnline />
            <ChatOnline />
            <ChatOnline />
            <ChatOnline />
            <ChatOnline />
            <ChatOnline />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Messenger
